import apiClient from './apiClient';

export const aiService = {
  analyzeRisk: async (patientData) => {
    // Assuming backend handles the AI model prediction under /risk
    return await apiClient.post('/risk/analyze', patientData);
  },
  
  getRiskHistory: async (patientId) => {
    return await apiClient.get(`/risk/history/${patientId}`);
  },

  getHealthAlerts: async () => {
    // If backend provides an alerts endpoint generated by AI
    return await apiClient.get('/alerts');
  }
};
